LIBS  = -lkernel32 -luser32 -lgdi32 -lopengl32
CFLAGS = -Wall
CC = cc
# Should be equivalent to your list of C files, if you don't build selectively
SRC=$(wildcard *.c)

test: $(SRC)
    cc -o $@ $^ $(CFLAGS) $(LIBS)


all: example1_1 example1_2 example1_3 example1_4 example1_5 example2_1 example3_1 example3_2 example3_3 example3_4 example3_5 example3_6 example3_7
CC = cc
example1_1: example1_1.c
	$(CC) example1_1.c -o example1_1 -framework OpenGL -lOpenVG -lp5graphics -lglfw -I. -I../include -L.

example1_2: example1_2.c
		$(CC) example1_2.c -o example1_2 -framework OpenGL -lOpenVG -lp5graphics -lglfw -I. -I../include -L.

example1_3: example1_3.c
		$(CC) example1_3.c -o example1_3 -framework OpenGL -lOpenVG -lp5graphics -lglfw -I. -I../include -L.

example1_4: example1_4.c
		$(CC) example1_4.c -o example1_4 -framework OpenGL -lOpenVG -lp5graphics -lglfw -I. -I../include -L.

example1_5: example1_5.c
		$(CC) example1_5.c -o example1_5 -framework OpenGL -lOpenVG -lp5graphics -lglfw -I. -I../include -L.

example2_1: example2_1.c
		$(CC) example2_1.c -o example2_1 -framework OpenGL -lOpenVG -lp5graphics -lglfw -I. -I../include -L.

example3_1: example3_1.c
		$(CC) example3_1.c -o example3_1 -framework OpenGL -lOpenVG -lp5graphics -lglfw -I. -I../include -L.
		
example3_2: example3_2.c
		$(CC) example3_2.c -o example3_2 -framework OpenGL -lOpenVG -lp5graphics -lglfw -I. -I../include -L.
		
example3_3: example3_3.c
		$(CC) example3_3.c -o example3_3 -framework OpenGL -lOpenVG -lp5graphics -lglfw -I. -I../include -L.

example3_4: example3_4.c
		$(CC) example3_4.c -o example3_4 -framework OpenGL -lOpenVG -lp5graphics -lglfw -I. -I../include -L.

example3_5: example3_5.c
		$(CC) example3_5.c -o example3_5 -framework OpenGL -lOpenVG -lp5graphics -lglfw -I. -I../include -L.

example3_6: example3_6.c
		$(CC) example3_6.c -o example3_6 -framework OpenGL -lOpenVG -lp5graphics -lglfw -I. -I../include -L.

example3_7: example3_7.c
		$(CC) example3_7.c -o example3_7 -framework OpenGL -lOpenVG -lp5graphics -lglfw -I. -I../include -L.
		
clean: 
	rm example1_1 example1_2 example1_3 example1_4 example1_5 example2_1 example3_1 example3_2 example3_3 example3_4 example3_5 example3_6 example3_7